export const constant = {

    //Common Config Constants

    CONFIG_REQUEST: 'FETCH_COFIG_REQUEST',
    CONFIG_SUCCESS: 'FETCH_COFIG_SUCCESS',
    CONFIG_FAILURE: 'FETCH_COFIG_FAILURE',

    //Unit Filter 

    UNIT_FILTER_REQUEST: 'UNIT_FILTER_REQUEST',
    UNIT_FILTER_SUCCESS: 'UNIT_FILTER_SUCCESS',
    UNIT_FILTER_FAILURE: 'UNIT_FILTER_FAILURE',
};
