export const appConfigConstant = {
    CONFIG_REQUEST: 'FETCH_COFIG_REQUEST',
    CONFIG_SUCCESS: 'FETCH_COFIG_SUCCESS',
    CONFIG_FAILURE: 'FETCH_COFIG_FAILURE',

    //facilty detail
    FACILITY_REQUEST:'FETCH_FACILITY_REQUEST',
    FACILITY_SUCESS:'FETCH_FACILITY_SUCESS',
    FACILITY_FAILURE:'FETCH_FACILITY_FAILURE',
    
};
